team6-hrbank/sb02-hrbank-team6

src/main/java/com/team6/hrbank/dto/employee/EmployeeCreateRequest.java, src/main/java/com/team6/hrbank/dto/employee/EmployeeDto.java, src/main/java/com/team6/hrbank/dto/employee/EmployeeUpdateRequest.java, src/main/java/com/team6/hrbank/repository/EmployeeRepository.java, src/main/java/com/team6/hrbank/service/EmployeeService.java
=> [#11] 직원 등록 - EmployeeRepository 인터페이스 정의

src/main/java/com/team6/hrbank/mapper/DepartmentMapper.java, src/main/java/com/team6/hrbank/service/DepartmentServiceImpl.java
=> [#8] 부서 등록 기능 구현 - [#44] 서비스 구현체 및 매퍼 작성

src/main/java/com/team6/hrbank/service/FileMetadataService.java
=> FileMetadata 인터페이스 create 추가

src/main/java/com/team6/hrbank/controller/EmployeeController.java, src/main/java/com/team6/hrbank/exception/ErrorCode.java, src/main/java/com/team6/hrbank/mapper/EmployeeMapper.java, src/main/java/com/team6/hrbank/repository/EmployeeRepository.java, src/main/java/com/team6/hrbank/service/EmployeeServiceImpl.java, src/main/java/com/team6/hrbank/service/FileMetadataService.java
Resolves: #63 
: 직원 등록 서비스 구현
Resolves: #65 
: 프로필 이미지 등록 처리 
Resolves: #64 
: 직원 등록 컨트롤러 구현
Closes: #62
=> [#62] 직원 등록 기능 구현

src/main/java/com/team6/hrbank/controller/EmployeeController.java, src/main/java/com/team6/hrbank/service/EmployeeServiceImpl.java
Resolves: #67 
: 직원 상세 조회 서비스 구현 
Resolves: #68
: 직원 상세 조회 Controller 구현
=> [#66] 직원 상세 조회 기능 구현

src/main/java/com/team6/hrbank/entity/Employee.java, src/main/java/com/team6/hrbank/exception/ErrorCode.java, src/main/java/com/team6/hrbank/mapper/EmployeeMapper.java
=> [#100] MapStruct Mapper 오류 수정

src/main/java/com/team6/hrbank/controller/EmployeeController.java, src/main/java/com/team6/hrbank/service/EmployeeServiceImpl.java
=> [#104] 직원 삭제 기능 구현

src/main/java/com/team6/hrbank/controller/ChangeLogController.java, src/main/java/com/team6/hrbank/dto/changeLog/ChangeLogDto.java, src/main/java/com/team6/hrbank/dto/changeLog/ChangeLogSearchCondition.java, src/main/java/com/team6/hrbank/dto/changeLog/CursorPageResponseChangeLogDto.java, src/main/java/com/team6/hrbank/entity/ChangeLog.java, src/main/java/com/team6/hrbank/entity/ChangeType.java, src/main/java/com/team6/hrbank/repository/ChangeLogRepository.java, src/main/java/com/team6/hrbank/service/ChangeLogService.java, src/main/java/com/team6/hrbank/service/ChangeLogServiceImpl.java, src/main/java/com/team6/hrbank/specification/ChangeLogSpecifications.java
#78 ChangeLog 컨트롤러 생성
#79 ChangeLog Specification 클래스 생성
#113 ChangeLog Entity, ChangeType Enum 생성
#114 ChangeLog 서비스 구현
#115 ChangeLog 리포지토리 구현
#116 ChangeLog 조회 Dto 생성
=> [#76] 이력 목록 조회 개발

src/main/java/com/team6/hrbank/controller/ChangeLogController.java, src/main/java/com/team6/hrbank/dto/changeLog/DiffDto.java, src/main/java/com/team6/hrbank/entity/ChangeLogDetail.java, src/main/java/com/team6/hrbank/exception/ErrorCode.java, src/main/java/com/team6/hrbank/mapper/ChangeLogDetailMapper.java, src/main/java/com/team6/hrbank/mapper/ChangeLogMapper.java, src/main/java/com/team6/hrbank/repository/ChangeLogDetailRepository.java, src/main/java/com/team6/hrbank/service/ChangeLogService.java, src/main/java/com/team6/hrbank/service/ChangeLogServiceImpl.java
#121 ChangeLogMapper 생성
#122 ChangeLog 컨트롤러에 메서드 추가
#123 ChangeLogDetail 엔티티 생성
#124 ChangeLog 서비스에 메서드 추가
#125 ChangeLogDetail 조회 Dto 생성
#126 ChangeLogDetailMapper 생성
#130 ChangeLog, ChangeLogDetail 관련 에러코드 추가
=> [#111] 이력 변경 상세 내용 조회 개발

src/main/java/com/team6/hrbank/controller/DepartmentController.java, src/main/java/com/team6/hrbank/dto/department/CursorPageResponseDepartmentDto.java, src/main/java/com/team6/hrbank/dto/department/DepartmentSearchCondition.java, src/main/java/com/team6/hrbank/repository/DepartmentRepository.java, src/main/java/com/team6/hrbank/service/DepartmentService.java, src/main/java/com/team6/hrbank/service/DepartmentServiceImpl.java, src/main/java/com/team6/hrbank/specification/DepartmentSpecification.java
=> [#98] 부서 목록 조회 구현

src/main/java/com/team6/hrbank/controller/DashBoardController.java, src/main/java/com/team6/hrbank/entity/EmployeeState.java, src/main/java/com/team6/hrbank/repository/DepartmentStatsRepository.java, src/main/java/com/team6/hrbank/repository/EmployeeQueryRepository.java, src/main/java/com/team6/hrbank/repository/EmployeeStatsRepository.java, src/main/java/com/team6/hrbank/scheduler/DepartmentStatsScheduler.java, src/main/java/com/team6/hrbank/scheduler/EmployeeStatsScheduler.java, src/main/java/com/team6/hrbank/service/DepartmentStatsService.java, src/main/java/com/team6/hrbank/service/EmployeeStatsService.java, src/main/java/com/team6/hrbank/service/Impl/DepartmentStatsServiceImpl.java, src/main/java/com/team6/hrbank/service/Impl/EmployeeStatsServiceImpl.java, src/main/resources/schema.sql
solves: #134
solves: #135
solves: #136
solves: #141
=> [#134] 부서 별 분포 통계 기능 개발

src/main/java/com/team6/hrbank/controller/DashBoardController.java, src/main/java/com/team6/hrbank/entity/Employee.java, src/main/java/com/team6/hrbank/exception/ErrorCode.java, src/main/java/com/team6/hrbank/repository/PositionStatsRepository.java, src/main/java/com/team6/hrbank/scheduler/PositionStatsScheduler.java, src/main/java/com/team6/hrbank/service/Impl/DepartmentStatsServiceImpl.java, src/main/java/com/team6/hrbank/service/Impl/EmployeeStatsServiceImpl.java, src/main/java/com/team6/hrbank/service/Impl/PositionStatsServiceImpl.java, src/main/java/com/team6/hrbank/service/PositionStatsService.java
solves: #149 
solves: #150 
solves: #151
=> [#149] 직무 분포 통계 기능 개발

src/main/java/com/team6/hrbank/controller/EmployeeController.java, src/main/java/com/team6/hrbank/controller/FileMetadataController.java, src/main/java/com/team6/hrbank/exception/ErrorCode.java, src/main/java/com/team6/hrbank/repository/EmployeeQueryRepository.java, src/main/java/com/team6/hrbank/service/EmployeeService.java, src/main/java/com/team6/hrbank/service/EmployeeServiceImpl.java
=> [#167] 실시간 직원 수 집계 기능 개발

src/main/java/com/team6/hrbank/controller/EmployeeController.java, src/main/java/com/team6/hrbank/dto/employee/CursorPageResponseEmployeeDto.java, src/main/java/com/team6/hrbank/dto/employee/EmployeeDto.java, src/main/java/com/team6/hrbank/dto/employee/EmployeeSearchCondition.java, src/main/java/com/team6/hrbank/mapper/EmployeeMapper.java, src/main/java/com/team6/hrbank/repository/EmployeeRepository.java, src/main/java/com/team6/hrbank/repository/EmployeeRepositoryCustom.java, src/main/java/com/team6/hrbank/repository/EmployeeRepositoryCustomImpl.java, src/main/java/com/team6/hrbank/service/EmployeeService.java, src/main/java/com/team6/hrbank/service/EmployeeServiceImpl.java
- EmployeeSearchCondition DTO 생성
- EmployeeDto 및 CursorPageResponseEmployeeDto 생성
- EmployeeMapper 수정 및 Enum → String 매핑 추가
- EmployeeRepositoryCustom 및 EmployeeRepositoryCustomImpl 생성 및 QueryDSL 구현
- EmployeeService 인터페이스에 searchEmployees 메서드 추가
- EmployeeServiceImpl에 searchEmployees 메서드 구현
- EmployeeController에 직원 목록 조회 API 추가
- 필터링, 정렬, 커서 페이지네이션 기능 적용
Resolves: #159
Resolves: #160
Resolves: #119
Resolves: #120
Closes: #158
=> [#158] 직원 목록 조회 QueryDSL 구현

src/main/java/com/team6/hrbank/entity/Employee.java, src/main/java/com/team6/hrbank/service/EmployeeServiceImpl.java
- 직원 삭제 시 DB 삭제 대신 상태(EmployeeState)를 RESIGNED로 변경하는 방식으로 수정
-  Employee 엔티티에 changeState(EmployeeState state) 메서드 추가
Resloves: #165
Resolves: #166 
Closes: #164
=> [#164] 직원 삭제 수정

build.gradle, src/main/java/com/team6/hrbank/HrbankApplication.java, src/main/java/com/team6/hrbank/controller/DashBoardController.java, src/main/java/com/team6/hrbank/service/Impl/DepartmentStatsServiceImpl.java, src/main/java/com/team6/hrbank/service/Impl/EmployeeStatsServiceImpl.java, src/main/java/com/team6/hrbank/service/Impl/PositionStatsServiceImpl.java, src/main/java/com/team6/hrbank/service/PositionStatsService.java
=> [#176] 대시보드 통계 조회 기능 로컬 캐싱 도입

src/main/java/com/team6/hrbank/controller/EmployeeController.java, src/main/java/com/team6/hrbank/entity/ChangeLog.java, src/main/java/com/team6/hrbank/entity/ChangeLogDetail.java, src/main/java/com/team6/hrbank/exception/ErrorCode.java, src/main/java/com/team6/hrbank/repository/ChangeLogRepositoryCustomImpl.java, src/main/java/com/team6/hrbank/service/ChangeLogService.java, src/main/java/com/team6/hrbank/service/ChangeLogServiceImpl.java, src/main/java/com/team6/hrbank/service/EmployeeService.java, src/main/java/com/team6/hrbank/service/EmployeeServiceImpl.java
#140 ChangeLog 서비스에 메서드 추가
#142 Employee 컨트롤러에 적용
#143 Employee 서비스에 적용 
#152 ChangeLog, ChangeLogDetail 엔티티에 연관관계 추가
=> [#38] 이력 등록 개발

src/main/java/com/team6/hrbank/repository/EmployeeRepositoryCustomImpl.java, src/main/java/com/team6/hrbank/service/EmployeeServiceImpl.java
Resolves: #182 - 커서 페이지네이션 버그 수정
Resolves: #183 - idAfter 추가 정렬 로직 구현
Closes: #181
=> [#181] 직원 목록조회 커서개선

src/main/java/com/team6/hrbank/controller/ChangeLogController.java, src/main/java/com/team6/hrbank/dto/changeLog/CursorPageResponseChangeLogDto.java, src/main/java/com/team6/hrbank/repository/ChangeLogRepositoryCustom.java, src/main/java/com/team6/hrbank/repository/ChangeLogRepositoryCustomImpl.java, src/main/java/com/team6/hrbank/service/ChangeLogService.java, src/main/java/com/team6/hrbank/service/ChangeLogServiceImpl.java
#205 ipAddress로 조회 시에도 nextIdAfter 값 설정
#206 총 데이터 개수(totalElements) 구하는 로직 추가
#207 changeLog 목록 조회 시 발생하는 n+1 문제 해결
#208 count 값을 Long이 아닌 long으로 가져오도록 수정
=> [#204] 페이지네이션 구현 보완, N+1 문제 해결

src/main/java/com/team6/hrbank/dto/employee/EmployeeCreateRequest.java, src/main/java/com/team6/hrbank/dto/employee/EmployeeUpdateRequest.java, src/main/java/com/team6/hrbank/entity/Employee.java, src/main/java/com/team6/hrbank/exception/ErrorCode.java, src/main/java/com/team6/hrbank/mapper/EmployeeMapper.java, src/main/java/com/team6/hrbank/repository/EmployeeRepositoryCustomImpl.java, src/main/java/com/team6/hrbank/service/EmployeeServiceImpl.java
Resolves: #200 
- 직원 등록/조회 시 employeeName → name 필드 매핑 수정
Resolves: #201 
- 사원 번호 생성 시 hireDate 기준으로 생성으로 수정( 기존 : localDate.now().getYear() )
#202 
- 직원 목록 조회 시 커서 기반 페이지네이션 오류 수정 ( hasNext 수정 )
#203
- 직원 등록 시 position을 한글(label)로 입력할 수 있도록 수정 ( update 시 동일함 )
Closes: #199
=> [#199] 직원 등록/조회 기능 개선 및 페이지네이션 오류 수정

src/main/java/com/team6/hrbank/service/DepartmentStatsServiceImpl.java, src/main/java/com/team6/hrbank/service/EmployeeStatsServiceImpl.java, src/main/java/com/team6/hrbank/service/PositionStatsServiceImpl.java
solves: #211 
solves: #212 
solves: #213
=> [#211] 간단한 코드 리팩토링 및 로깅 추가

build.gradle, src/main/java/com/team6/hrbank/HrbankApplication.java, src/main/java/com/team6/hrbank/config/RedisCacheConfig.java, src/main/java/com/team6/hrbank/dto/employeestats/EmployeeDistributionDto.java, src/main/java/com/team6/hrbank/dto/employeestats/EmployeeTrendDto.java, src/main/java/com/team6/hrbank/service/DepartmentStatsServiceImpl.java, src/main/java/com/team6/hrbank/service/EmployeeStatsServiceImpl.java, src/main/java/com/team6/hrbank/service/PositionStatsServiceImpl.java
=> [#189] redis 글로벌 캐시 사용

src/main/java/com/team6/hrbank/mapper/EmployeeMapper.java
=> [#127] 직원 목록 조회 시 position을 한글 label로 반환하도록 수정

build.gradle, src/main/java/com/team6/hrbank/controller/BackupHistoryController.java, src/main/java/com/team6/hrbank/controller/ChangeLogController.java, src/main/java/com/team6/hrbank/controller/DashBoardController.java, src/main/java/com/team6/hrbank/controller/DepartmentController.java, src/main/java/com/team6/hrbank/controller/EmployeeController.java, src/main/java/com/team6/hrbank/controller/FileMetadataController.java, src/main/java/com/team6/hrbank/service/EmployeeStatsServiceImpl.java, src/main/java/com/team6/hrbank/service/PositionStatsServiceImpl.java, src/main/java/com/team6/hrbank/swagger/BackupHistoryApi.java, src/main/java/com/team6/hrbank/swagger/ChangeLogApi.java, src/main/java/com/team6/hrbank/swagger/DashBoardApi.java, src/main/java/com/team6/hrbank/swagger/DepartmentApi.java, src/main/java/com/team6/hrbank/swagger/EmployeeApi.java, src/main/java/com/team6/hrbank/swagger/FileMetadataApi.java
=> [#221] API 문서화를 위한 Controller 인터페이스 추가

src/main/java/com/team6/hrbank/controller/EmployeeController.java, src/main/java/com/team6/hrbank/service/EmployeeServiceImpl.java, src/main/java/com/team6/hrbank/service/FileMetadataService.java
controller 에서 delete 반환 타입 EmployeeDto -> Void
직원 삭제 시 프로필 삭제 주석 제거
=> 직원 관리 삭제 fix

src/main/resources/schema.sql
=> [#230] 스키마 최종 수정

build.gradle, src/main/java/com/team6/hrbank/HrbankApplication.java, src/main/java/com/team6/hrbank/config/JasyptConfig.java, src/main/java/com/team6/hrbank/service/EmployeeServiceImpl.java, src/main/resources/application.yml
=> [04/28] 1차 Release: v1.0.0
